export default [
  "Sean Hamilton - Chairman",
  "Mike Agee",
  "Randall Alcorn",
  "Jeff Baker",
  "Greg Beck",
  "Mike Cummings",
  `John “Fuji” Damron`,
  "Jason Davis",
  "Jeremiah Duerson",
  "Joe Duerson",
  "Bobby Lakes",
  "Steve Marino",
  "Rodney Rhodus",
  "Bryan Tucker",
  "Rick Whitesides",
  "Ed Wilson",
]
